csvPath : "/users/satishbomma/PycharmProjects/appSearchData/netflix_titles.csv"
Engine : "netflix-engine"
cloud_url: "https://7c099a726e3b4e1db96decda426c88ae.ent-search.us-west1.gcp.cloud.es.io"
pvt_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
batch_size: 100
